export { default as authRoutes } from './authRoutes'
export { default as userRoutes } from './userRoutes'
export { default as statusRoutes } from './statusRoutes'
export { default as starredMessageRoutes } from './starredMessageRoutes'
export { default as groupRoutes } from './groupRoutes'
export { default as chatRoutes } from './chatRoutes'